var petDog = "Rex";
var petCat = "Pepper";
Console.log(petDog);
Console.log(petCat);
Console.log("My pet dog's name is: " + petDog);
Console.log("My pet cat's name is: " + petCat);
var catSound = "purr";
var dogSound = "woof";
Console.log(petCat + " says " + catSound);
catSound = "meow";
Console.log(petCat + " now says " + catSound);